version: '{build}'
shallow_clone: true

platform: x64

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  fast_finish: false

before_build:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "CI"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - where dotnet.exe
  - dotnet --info

build_script:
  - dotnet build Vrp.csproj

test_script:
  - dotnet run --project Vrp.csproj

